using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace ObjectPoolLinter
{
    /// <summary>
    /// One class that passed <see cref="ObjectPoolGenerator"/>'s checks, with everything the writer
    /// below needs to emit its pool.
    /// </summary>
    internal sealed class PoolRequest
    {
        internal PoolRequest(
            INamedTypeSymbol type,
            string poolName,
            string accessibility,
            int initialCapacity,
            List<IMethodSymbol> constructors,
            List<ITypeParameterSymbol> typeParameters,
            Location location)
        {
            Type = type;
            PoolName = poolName;
            Accessibility = accessibility;
            InitialCapacity = initialCapacity;
            Constructors = constructors;
            TypeParameters = typeParameters;
            Location = location;

            var containing = type.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : type.ContainingNamespace.ToDisplayString() + ".";

            // A backtick is legal in a hint name but reads as a broken path in build output, so the
            // arity is spelled out instead. Two pools only share a hint name when they would also
            // collide as types, which is what the generator reports OPL005 for.
            var arity = typeParameters.Count == 0
                ? string.Empty
                : "_" + typeParameters.Count.ToString(CultureInfo.InvariantCulture);

            HintName = containing + poolName + arity + ".g.cs";
        }

        internal INamedTypeSymbol Type { get; }

        internal string PoolName { get; }

        internal string Accessibility { get; }

        internal int InitialCapacity { get; }

        internal List<IMethodSymbol> Constructors { get; }

        internal List<ITypeParameterSymbol> TypeParameters { get; }

        internal Location Location { get; }

        internal string HintName { get; }
    }

    /// <summary>
    /// Writes the pool source for a <see cref="PoolRequest"/>. The output stays inside C# 7.3 so it
    /// compiles on every Unity version the analyzer supports, and every type it names is fully
    /// qualified so no <c>using</c> in the consumer's file can change what it means.
    /// </summary>
    internal static class PoolSourceWriter
    {
        private const string Stack = "global::System.Collections.Generic.Stack";
        private const string Field = "s_free";

        private static readonly SymbolDisplayFormat Qualified = SymbolDisplayFormat.FullyQualifiedFormat;

        internal static string Write(PoolRequest request)
        {
            var type = request.Type.ToDisplayString(Qualified);
            var shortName = request.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            var poolReference = request.PoolName + TypeArgumentList(request.TypeParameters);

            var builder = new StringBuilder();
            builder.Append("// <auto-generated/>\n");
            builder.Append("#pragma warning disable\n\n");

            var indent = string.Empty;
            if (!request.Type.ContainingNamespace.IsGlobalNamespace)
            {
                builder.Append("namespace ").Append(request.Type.ContainingNamespace.ToDisplayString()).Append("\n{\n");
                indent = "    ";
            }

            var body = indent + "    ";

            builder.Append(indent).Append("/// <summary>\n");
            builder.Append(indent).Append("/// Object pool for <c>").Append(shortName).Append("</c>, generated from its [ObjectPool]\n");
            builder.Append(indent).Append("/// attribute. Not thread-safe, which is enough for Unity's main-thread messages.\n");
            builder.Append(indent).Append("/// </summary>\n");
            builder.Append(indent).Append(request.Accessibility).Append(" static partial class ").Append(poolReference).Append('\n');
            AppendConstraints(builder, indent + "    ", request.TypeParameters);
            builder.Append(indent).Append("{\n");

            var capacity = request.InitialCapacity > 0
                ? request.InitialCapacity.ToString(CultureInfo.InvariantCulture)
                : string.Empty;

            builder.Append(body).Append("private static readonly ").Append(Stack).Append('<').Append(type).Append("> ").Append(Field)
                   .Append(" = new ").Append(Stack).Append('<').Append(type).Append(">(").Append(capacity).Append(");\n\n");

            builder.Append(body).Append("/// <summary>How many instances are waiting in the pool.</summary>\n");
            builder.Append(body).Append("public static int CountInactive\n");
            builder.Append(body).Append("{\n");
            builder.Append(body).Append("    get { return ").Append(poolReference).Append('.').Append(Field).Append(".Count; }\n");
            builder.Append(body).Append("}\n");

            foreach (var constructor in request.Constructors)
                AppendGet(builder, body, request, type, shortName, poolReference, constructor);

            AppendReturn(builder, body, type, shortName, poolReference);

            builder.Append(indent).Append("}\n");

            if (indent.Length > 0) builder.Append("}\n");

            return builder.ToString();
        }

        private static void AppendGet(
            StringBuilder builder,
            string body,
            PoolRequest request,
            string type,
            string shortName,
            string poolReference,
            IMethodSymbol constructor)
        {
            var local = LocalName(constructor);
            var signature = shortName + "(" + Parameters(constructor, includeDefaults: false, includeParams: false, includeTypes: true, includeNames: false) + ")";
            var forwarded = Arguments(constructor);

            builder.Append('\n');
            builder.Append(body).Append("/// <summary>\n");
            builder.Append(body).Append("/// Takes an instance out of the pool, or constructs one when the pool is empty.\n");
            builder.Append(body).Append("/// Forwards to <c>new ").Append(signature).Append("</c>.\n");
            builder.Append(body).Append("/// </summary>\n");
            builder.Append(body).Append("public static ").Append(type).Append(" Get(")
                   .Append(Parameters(constructor, includeDefaults: true, includeParams: true, includeTypes: true, includeNames: true))
                   .Append(")\n");
            builder.Append(body).Append("{\n");
            builder.Append(body).Append("    if (").Append(poolReference).Append('.').Append(Field).Append(".Count == 0) return new ")
                   .Append(type).Append('(').Append(forwarded).Append(");\n\n");
            builder.Append(body).Append("    ").Append(type).Append(' ').Append(local).Append(" = ")
                   .Append(poolReference).Append('.').Append(Field).Append(".Pop();\n");
            builder.Append(body).Append("    Reinitialize(").Append(local);
            if (forwarded.Length > 0) builder.Append(", ").Append(forwarded);
            builder.Append(");\n");
            builder.Append(body).Append("    return ").Append(local).Append(";\n");
            builder.Append(body).Append("}\n\n");

            builder.Append(body).Append("/// <summary>\n");
            builder.Append(body).Append("/// Implement this in your own <c>static partial class ").Append(request.PoolName)
                   .Append("</c> to put a recycled\n");
            builder.Append(body).Append("/// instance back into the state <c>new ").Append(signature).Append("</c> would have left it in.\n");
            builder.Append(body).Append("/// Left unimplemented, the call above is erased and the instance keeps whatever state it\n");
            builder.Append(body).Append("/// had when it was returned.\n");
            builder.Append(body).Append("/// </summary>\n");
            builder.Append(body).Append("static partial void Reinitialize(").Append(type).Append(' ').Append(local);
            var declared = Parameters(constructor, includeDefaults: false, includeParams: false, includeTypes: true, includeNames: true);
            if (declared.Length > 0) builder.Append(", ").Append(declared);
            builder.Append(");\n");
        }

        private static void AppendReturn(StringBuilder builder, string body, string type, string shortName, string poolReference)
        {
            builder.Append('\n');
            builder.Append(body).Append("/// <summary>\n");
            builder.Append(body).Append("/// Hands an instance back to the pool. Nothing checks whether it is already in there, so\n");
            builder.Append(body).Append("/// return each instance exactly once.\n");
            builder.Append(body).Append("/// </summary>\n");
            builder.Append(body).Append("public static void Return(").Append(type).Append(" instance)\n");
            builder.Append(body).Append("{\n");
            builder.Append(body).Append("    if (instance == null) throw new global::System.ArgumentNullException(\"instance\");\n\n");
            builder.Append(body).Append("    OnReturn(instance);\n");
            builder.Append(body).Append("    ").Append(poolReference).Append('.').Append(Field).Append(".Push(instance);\n");
            builder.Append(body).Append("}\n\n");

            builder.Append(body).Append("/// <summary>\n");
            builder.Append(body).Append("/// Implement this to release whatever a <c>").Append(shortName).Append("</c> is holding on to before\n");
            builder.Append(body).Append("/// it waits in the pool: references that would otherwise stay alive, handlers, buffers.\n");
            builder.Append(body).Append("/// </summary>\n");
            builder.Append(body).Append("static partial void OnReturn(").Append(type).Append(" instance);\n\n");

            builder.Append(body).Append("/// <summary>Drops every instance waiting in the pool.</summary>\n");
            builder.Append(body).Append("public static void Clear()\n");
            builder.Append(body).Append("{\n");
            builder.Append(body).Append("    ").Append(poolReference).Append('.').Append(Field).Append(".Clear();\n");
            builder.Append(body).Append("}\n");
        }

        private static string TypeArgumentList(List<ITypeParameterSymbol> typeParameters)
        {
            if (typeParameters.Count == 0) return string.Empty;

            var builder = new StringBuilder("<");
            for (var i = 0; i < typeParameters.Count; i++)
            {
                if (i > 0) builder.Append(", ");
                builder.Append(typeParameters[i].Name);
            }

            return builder.Append('>').ToString();
        }

        private static void AppendConstraints(StringBuilder builder, string indent, List<ITypeParameterSymbol> typeParameters)
        {
            foreach (var parameter in typeParameters)
            {
                var parts = new List<string>();

                // unmanaged and notnull also set the value-type / reference-type flags, so the most
                // specific one has to win here or the emitted clause is both wrong and redundant.
                if (parameter.HasReferenceTypeConstraint) parts.Add("class");
                else if (parameter.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
                else if (parameter.HasValueTypeConstraint) parts.Add("struct");
                else if (parameter.HasNotNullConstraint) parts.Add("notnull");

                foreach (var constraint in parameter.ConstraintTypes)
                    parts.Add(constraint.ToDisplayString(Qualified));

                if (parameter.HasConstructorConstraint) parts.Add("new()");

                if (parts.Count == 0) continue;

                builder.Append(indent).Append("where ").Append(parameter.Name).Append(" : ")
                       .Append(string.Join(", ", parts.ToArray())).Append('\n');
            }
        }

        private static string Parameters(IMethodSymbol constructor, bool includeDefaults, bool includeParams, bool includeTypes, bool includeNames)
        {
            var builder = new StringBuilder();

            for (var i = 0; i < constructor.Parameters.Length; i++)
            {
                if (i > 0) builder.Append(", ");

                var parameter = constructor.Parameters[i];

                if (includeParams && parameter.IsParams) builder.Append("params ");
                builder.Append(RefKindPrefix(parameter.RefKind));

                if (includeTypes) builder.Append(parameter.Type.ToDisplayString(Qualified));
                if (includeTypes && includeNames) builder.Append(' ');
                if (includeNames) builder.Append(Identifier(parameter.Name));

                if (includeDefaults && parameter.HasExplicitDefaultValue && TryFormatDefault(parameter, out var literal))
                    builder.Append(" = ").Append(literal);
            }

            return builder.ToString();
        }

        private static string Arguments(IMethodSymbol constructor)
        {
            var builder = new StringBuilder();

            for (var i = 0; i < constructor.Parameters.Length; i++)
            {
                if (i > 0) builder.Append(", ");

                var parameter = constructor.Parameters[i];

                // An `in` argument may be passed without the modifier; `ref` may not.
                if (parameter.RefKind == RefKind.Ref) builder.Append("ref ");
                builder.Append(Identifier(parameter.Name));
            }

            return builder.ToString();
        }

        private static string RefKindPrefix(RefKind refKind)
        {
            switch (refKind)
            {
                case RefKind.Ref: return "ref ";
                case RefKind.In: return "in ";
                default: return string.Empty;
            }
        }

        private static string LocalName(IMethodSymbol constructor)
        {
            var name = "instance";

            while (true)
            {
                var taken = false;
                foreach (var parameter in constructor.Parameters)
                {
                    if (parameter.Name == name)
                    {
                        taken = true;
                        break;
                    }
                }

                if (!taken) return name;
                name = "_" + name;
            }
        }

        private static string Identifier(string name)
        {
            return SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;
        }

        private static bool TryFormatDefault(IParameterSymbol parameter, out string literal)
        {
            literal = string.Empty;

            var type = parameter.Type.ToDisplayString(Qualified);
            var value = parameter.ExplicitDefaultValue;

            if (value == null)
            {
                // An unconstrained type parameter is neither a reference type nor a value type here,
                // and only default(T) is legal for it.
                literal = parameter.Type.IsReferenceType ? "null" : "default(" + type + ")";
                return true;
            }

            if (parameter.Type.TypeKind == TypeKind.Enum)
            {
                literal = "(" + type + ")(" + Convert.ToString(value, CultureInfo.InvariantCulture) + ")";
                return true;
            }

            switch (value)
            {
                case bool flag:
                    literal = flag ? "true" : "false";
                    return true;
                case string text:
                    literal = SymbolDisplay.FormatLiteral(text, quote: true);
                    return true;
                case char character:
                    literal = SymbolDisplay.FormatLiteral(character, quote: true);
                    return true;
                case float single:
                    if (float.IsNaN(single) || float.IsInfinity(single)) return false;
                    literal = single.ToString("R", CultureInfo.InvariantCulture) + "F";
                    return true;
                case double real:
                    if (double.IsNaN(real) || double.IsInfinity(real)) return false;
                    literal = real.ToString("R", CultureInfo.InvariantCulture) + "D";
                    return true;
                case decimal fixedPoint:
                    literal = fixedPoint.ToString(CultureInfo.InvariantCulture) + "M";
                    return true;
                case long wide:
                    literal = wide.ToString(CultureInfo.InvariantCulture) + "L";
                    return true;
                case ulong unsignedWide:
                    literal = unsignedWide.ToString(CultureInfo.InvariantCulture) + "UL";
                    return true;
                case uint unsigned:
                    literal = unsigned.ToString(CultureInfo.InvariantCulture) + "U";
                    return true;
                case int whole:
                    literal = whole.ToString(CultureInfo.InvariantCulture);
                    return true;
                case short small:
                    literal = small.ToString(CultureInfo.InvariantCulture);
                    return true;
                case ushort unsignedSmall:
                    literal = unsignedSmall.ToString(CultureInfo.InvariantCulture);
                    return true;
                case byte singleByte:
                    literal = singleByte.ToString(CultureInfo.InvariantCulture);
                    return true;
                case sbyte signedByte:
                    literal = signedByte.ToString(CultureInfo.InvariantCulture);
                    return true;
                default:
                    // Anything else is left off the signature: the parameter simply becomes required,
                    // which is a compile error at the call site rather than a wrong default.
                    return false;
            }
        }
    }
}
